//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrovaControl8.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public System.DateTime Date { get; set; }
        public decimal Mark { get; set; }
        public string Name { get; set; }
    }
}
